version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: islam
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bloom-administration-dev-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: localhost
      DB_DATABASE: bloom-administration-dev-db
      DB_USER: islam
      DB_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command: ["start-dev"]
    depends_on:
      - postgres
    network_mode: host

  administration-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bloom-administration-dev-db
      SPRING_DATASOURCE_USERNAME: islam
      SPRING_DATASOURCE_PASSWORD: admin
      KEYCLOAK_URL: http://localhost:8080
      JWT_SET_URI: http://localhost:8080/realms/dev/protocol/openid-connect/certs
    depends_on:
      - postgres
      - keycloak
    network_mode: host

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - administration-app
    network_mode: host

volumes:
  postgres_data:
