version: '3.8'

services:
#  postgres:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: islam
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: bloom-administration-dev-db
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: localhost
      DB_DATABASE: bloom-administration-dev-db
      DB_USER: islam
      DB_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command: [ "start-dev" ]
#    depends_on:
#      - postgres
    network_mode: host

  administration-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://45.8.116.32:5432/bloom-administration-dev-db
      SPRING_DATASOURCE_USERNAME: islam
      SPRING_DATASOURCE_PASSWORD: admin
      KEYCLOAK_URL: http://keycloak:8080
      JWT_SET_URI: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
    depends_on:
#      - postgres
      - keycloak
    network_mode: host
    ports:
      - 9090:9090
    dns:
      - 8.8.8.8
      - 8.8.4.4

#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80
#    depends_on:
#      - administration-app
#    networks:
#      - backend
#      - frontend

#networks:
#  backend:
#  frontend:

volumes:
  postgres_data:
