version: '3.8'

services:
  #  postgres:
  #    image: postgres:14
  #    environment:
  #      POSTGRES_USER: islam
  #      POSTGRES_PASSWORD: admin
  #      POSTGRES_DB: bloom-administration-dev-db
  #    ports:
  #      - 5432:5432
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    networks:
  #      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: 192.168.1.33
      DB_DATABASE: bloom_administration_dev_db
      DB_USER: islam
      DB_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_PORT: 8080
      KC_HOSTNAME: 45.8.116.32
      KC_HOSTNAME_ADMIN_URL: http://45.8.116.32:8080/
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_FRONTEND_URL: http://45.8.116.32:8080/
    command: [ "start-dev"]
    #    depends_on:
    #      - postgres
    ports:
      - 8080:8080
      - 8443:8443

  administration-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.33:5432/bloom_administration_dev_db
      SPRING_DATASOURCE_USERNAME: islam
      SPRING_DATASOURCE_PASSWORD: admin
      KEYCLOAK_URL: http://keycloak:8080/
      JWT_SET_URI: http://keycloak:8080/realms/dev/protocol/openid-connect/certs
    depends_on:
      #      - postgres
      - keycloak
    ports:
      - 9090:9090
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - backend

#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80
#    depends_on:
#      - administration-app
#    networks:
#      - backend
#      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres_data:


