spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.33:5432/administration
    username: administration
    password: tS8WybXT8mUCV08jmuuU
    hikari:
      minimumIdle: ${HCP_MIN_IDL:2}
      idleTimeout: ${HCP_IDLE_TIMEOUT:60000}
      connectionTimeout: ${HCP_CONN_TIMEOUT:30000}
      maxLifetime: ${HCP_MAX_LIFETIME:300000}
      maximumPoolSize: 50
      connection-test-query: SELECT 1
      poolName: SpringBootJPAHikariCP
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
    locations: classpath:db/migration
  mail:
    host: mail.bloooom.kz
    port: 587
    username: no-reply@bloooom.kz
    password: ITbloooom2024$
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:http://keycloak.bloooom.kz:8080/realms/dev/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            token-uri: ${CLIENT_TOKEN_URL:http://keycloak.bloooom.kz:8080/realms/dev/protocol/openid-connect/token}
        registration:
          keycloak:
            client-id: ${CLIENT_ID:bloom-core}
            client-secret: ${CLIENT_SECRET:DO9gJAnWW1vilaB1cJnB1BZ3nmX4ccZ3}
            authorization-grant-type: client_credentials

springdoc:
  swagger-ui:
    configUrl: ${SWAGGER_CONFIG_UI:/api/v1/api-docs/swagger-config}
    disable-swagger-default-url: true
    url: ${SWAGGER_UI:/api/v1/api-docs}
    doc-expansion: none
  api-docs:
    path: /api/v1/api-docs
    version: openapi_3_0
swagger:
  url: ${SWAGGER_SERVER_URL:http://api.bloooom.kz:8443}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info, env, beans'
    jmx:
      exposure:
        include: 'health, prometheus, info, env, beans'
  endpoint:
    metrics:
      enabled: true
  health:
    mail:
      enabled: false
server:
  compression:
    enabled: true
  port: 8087
  address: 0.0.0.0
  forward-headers-strategy: framework

bloom:
  stage: ${BLOOM_STAGE:DEV}

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://keycloak.bloooom.kz:8080}
  realm: ${REALM:dev}
  resource: ${CLIENT_ID:bloom-core}
  client-secret: ${CLIENT_SECRET:DO9gJAnWW1vilaB1cJnB1BZ3nmX4ccZ3}
  username: ${REALM_USERNAME:bloom-admin@bloom.kz}
  password: ${REALM_USER_PASSWORD:PQzmBchnP4LduQu}

logging:
  level:
    org.flywaydb.core: DEBUG


