spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bloom_administration_dev_db
    username: islam
    password: admin
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:http://192.168.1.33:7070/realms/dev/protocol/openid-connect/certs}
      client:
        provider:
          keycloak:
            token-uri: ${CLIENT_TOKEN_URL:http://192.168.1.33:7070/realms/dev/protocol/openid-connect/token}
        registration:
          keycloak:
            client-id: ${CLIENT_ID:bloom-core}
            client-secret: ${CLIENT_SECRET:BCVz6t5NKQZbvcCGOyshvqimVSBeueJM}
            authorization-grant-type: client_credentials

springdoc:
  swagger-ui:
    configUrl: ${SWAGGER_CONFIG_UI:/api/v1/api-docs/swagger-config}
    disable-swagger-default-url: true
    url: ${SWAGGER_UI:/api/v1/api-docs}
    doc-expansion: none
  api-docs:
    path: /api/v1/api-docs
    version: openapi_3_0
swagger:
  url: ${SWAGGER_SERVER_URL:192.168.1.33:9090}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info, env, beans'
    jmx:
      exposure:
        include: 'health, prometheus, info, env, beans'
  endpoint:
    metrics:
      enabled: true
  health:
    mail:
      enabled: false
server:
  compression:
    enabled: true
  port: 9090
  forward-headers-strategy: framework

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://192.168.1.33:7070}
  realm: ${REALM:dev}
  resource: ${CLIENT_ID:bloom-core}
  client-secret: ${CLIENT_SECRET:BCVz6t5NKQZbvcCGOyshvqimVSBeueJM}
  username: ${REALM_USERNAME:bloom-admin@bloom.kz}
  password: ${REALM_USER_PASSWORD:12345}

logging:
  level:
    org.flywaydb.core: DEBUG

