package kz.bloooom.administration.contant;

import lombok.experimental.UtilityClass;

@UtilityClass
public class ErrorCodeConstant {
    public final String USER_WITH_THIS_ID_DOEST_EXISTS = "USER_WITH_THIS_ID_DOEST_EXISTS";
    public final String USER_EMAIL_ALREADY_EXIST = "USER_EMAIL_ALREADY_EXIST";
    public final String WRONG_NUMBER_FORMAT = "WRONG_NUMBER_FORMAT";
    public final String USER_PHONE_NUMBER_ALREADY_EXIST = "USER_PHONE_NUMBER_ALREADY_EXIST";
    public final String WRONG_LOGIN_OR_PASSWORD = "WRONG_LOGIN_OR_PASSWORD";
    public final String CREATE_KEYCLOAK_USER_ERROR = "CREATE_KEYCLOAK_USER_ERROR";
    public final String REFRESH_TOKEN_INCORRECT = "REFRESH_TOKEN_INCORRECT";
    public final String USERNAME_INCORRECT = "USERNAME_INCORRECT";
    public final String USER_WITH_THIS_EMAIL_NOT_FOUND = "USER_WITH_THIS_EMAIL_NOT_FOUND";
    public final String ROLE_WITH_THIS_ID_DOEST_EXISTS = "ROLE_WITH_THIS_ID_DOEST_EXISTS";
    public final String COMPANY_TYPE_WITH_THIS_ID_DOEST_EXISTS = "COMPANY_TYPE_WITH_THIS_ID_DOEST_EXISTS";
    public final String COMPANY_TYPE_THIS_CODE_DOEST_EXISTS = "COMPANY_TYPE_THIS_CODE_DOEST_EXISTS";
    public final String ROLE_WITH_THIS_CODE_DOEST_EXISTS = "ROLE_WITH_THIS_CODE_DOEST_EXISTS";
    public final String USER_NOT_FOUNT = "USER_NOT_FOUNT";
    public final String USER_NOT_VERIFY_EMAIL = "USER_NOT_VERIFY_EMAIL";
    public final String PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH";
    public final String COMPANY_WITH_THIS_ID_DOEST_EXISTS = "COMPANY_WITH_THIS_ID_DOEST_EXISTS";
    public final String STATUS_WITH_THIS_ID_DOEST_EXISTS = "STATUS_WITH_THIS_ID_DOEST_EXISTS";
    public final String STATUS_WITH_THIS_CODE_DOEST_EXISTS = "STATUS_WITH_THIS_CODE_DOEST_EXISTS";
    public final String MAILING_ERROR = "MAILING_ERROR";
    public final String RESET_CODE_INVALID = "RESET_CODE_INVALID";
    public final String RESET_CODE_EXPIRED = "RESET_CODE_EXPIRED";
    public final String SUBSCRIPTION_TYPE_WITH_THIS_ID_DOEST_EXISTS = "SUBSCRIPTION_TYPE_WITH_THIS_ID_DOEST_EXISTS";
    public final String SUBSCRIPTION_TYPE_WITH_THIS_CODE_DOEST_EXISTS = "SUBSCRIPTION_TYPE_WITH_THIS_CODE_DOEST_EXISTS";
    public final String SUBSCRIPTION_STATUS_WITH_THIS_ID_DOEST_EXISTS = "SUBSCRIPTION_STATUS_WITH_THIS_ID_DOEST_EXISTS";
    public final String SUBSCRIPTION_STATUS_WITH_THIS_CODE_DOEST_EXISTS = "SUBSCRIPTION_STATUS_WITH_THIS_CODE_DOEST_EXISTS";
    public final String USER_WITH_THIS_KEYCLOAK_NOT_FOUND = "USER_WITH_THIS_KEYCLOAK_NOT_FOUND";
    public final String ORDER_STATUS_WITH_THIS_ID_DOEST_EXISTS = "ORDER_STATUS_WITH_THIS_ID_DOEST_EXISTS";
    public final String ORDER_STATUS_WITH_THIS_CODE_DOEST_EXISTS = "ORDER_STATUS_WITH_THIS_CODE_DOEST_EXISTS";
    public final String BOUQUET_WITH_THIS_ID_DOEST_EXISTS = "BOUQUET_WITH_THIS_ID_DOEST_EXISTS";
    public final String ORDER_WITH_THIS_ID_DOEST_EXISTS = "ORDER_WITH_THIS_ID_DOEST_EXISTS";
    public final String SUBSCRIPTION_WITH_THIS_ID_DOEST_EXISTS = "SUBSCRIPTION_WITH_THIS_ID_DOEST_EXISTS";
    public final String ERROR_WHEN_FILE_STORE = "ERROR_WHEN_FILE_STORE";
    public final String BOUQUET_STYLE_WITH_THIS_ID_DOEST_EXISTS = "BOUQUET_STYLE_WITH_THIS_ID_DOEST_EXISTS";
    public final String WATER_CARE_WITH_THIS_ID_DOEST_EXISTS = "WATER_CARE_WITH_THIS_ID_DOEST_EXISTS";
    public final String STEM_CARE_WITH_THIS_ID_DOEST_EXISTS = "STEM_CARE_WITH_THIS_ID_DOEST_EXISTS";
    public final String TEMPERATURA_CARE_WITH_THIS_ID_DOEST_EXISTS = "TEMPERATURA_CARE_WITH_THIS_ID_DOEST_EXISTS";
    public final String COUNTRY_WITH_THIS_ID_DOEST_EXISTS = "COUNTRY_WITH_THIS_ID_DOEST_EXISTS";
    public final String FLOWER_VARIETY_THIS_ID_DOEST_EXISTS = "FLOWER_VARIETY_THIS_ID_DOEST_EXISTS";
    public final String FLOWER_THIS_ID_DOEST_EXISTS = "FLOWER_THIS_ID_DOEST_EXISTS";
    public final String ELEMENT_WITH_THIS_ID_DOEST_EXISTS = "ELEMENT_WITH_THIS_ID_DOEST_EXISTS";
    public final String BRANCH_WITH_THIS_ID_DOEST_EXISTS = "BRANCH_WITH_THIS_ID_DOEST_EXISTS";
    public final String PASSWORDS_NOT_SAME = "PASSWORDS_NOT_SAME";
    public final String EMPLOYEE_NOT_FOUNT = "EMPLOYEE_NOT_FOUNT";
    public final String ADDRESS_WITH_THIS_ID_DOEST_EXISTS = "ADDRESS_WITH_THIS_ID_DOEST_EXISTS";
    public final String EMPLOYEE_WITH_THIS_KEYCLOAK_NOT_FOUND = "EMPLOYEE_WITH_THIS_KEYCLOAK_NOT_FOUND";
    public final String ORDER_ADDRESS_WITH_THIS_ID_DOEST_EXISTS = "ORDER_ADDRESS_WITH_THIS_ID_DOEST_EXISTS";
    public final String PRICE_IN_THIS_RANGE_EXITS_DOEST_EXISTS = "PRICE_IN_THIS_RANGE_EXITS_DOEST_EXISTS";
    public final String TRANSACTION_STATUS_WITH_THIS_ID_DOEST_EXISTS = "TRANSACTION_STATUS_WITH_THIS_ID_DOEST_EXISTS";
    public final String TRANSACTION_WITH_THIS_ID_DOEST_EXISTS = "TRANSACTION_WITH_THIS_ID_DOEST_EXISTS";
    public final String TRANSACTION_TYPE_WITH_THIS_ID_DOEST_EXISTS = "TRANSACTION_TYPE_WITH_THIS_ID_DOEST_EXISTS";
    public final String NOT_ENOUGH_MONEY = "NOT_ENOUGH_MONEY";
    public final String NOT_CHANGES = "NOT_CHANGES";
    public final String VALID_FROM_ARRIVED = "VALID_FROM_ARRIVED";
    public final String VALID_TO_PASSED = "VALID_TO_PASSED";
    public final String DATA_NON_VALID = "DATA_NON_VALID";

}
